# Uncomment the next line to define a global platform for your project
 platform :ios, '9.0'


target 'BirdConstructionApp' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for BirdConstructionApp

pod 'Firebase/Core'
pod 'Firebase/Database'
pod 'Firebase/Auth'

  #pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

  target 'BirdConstructionAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'BirdConstructionApp-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for BirdConstructionApp-tvOS

  target 'BirdConstructionApp-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
