# Uncomment the next line to define a global platform for your project
 platform :ios, '9.0'

pod 'Firebase/Core','~> 4.13.0'
pod 'Firebase/Database'
pod 'Firebase/Auth'
pod 'Firebase/Functions'

target 'BirdConstructionApp' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for BirdConstructionApp

  target 'BirdConstructionAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'BirdConstructionApp-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for BirdConstructionApp-tvOS

  target 'BirdConstructionApp-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
